name = "Curve25519"
uuid = "25832199-8a4b-40f8-aacc-9f7ea667c83d"
authors = ["Bogdan Opanchuk <bogdan@opanchuk.net>"]
version = "0.1.0"

[deps]
DarkIntegers = "95d18f7b-8dde-4426-a3cb-b3b9e7df9890"
DarkCurves = "eb74ef6d-f479-4c54-be43-bc7ae9988d2f"
ConstantTime = "adc38e39-84cc-4087-89ab-f4eae76b2d15"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DarkCurves = "~0.2.0"
DarkIntegers = "~0.1.4"
Jute = "~0.2.5"
julia = "^1.0.0"
ConstantTime = "~0.1.1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Jute = "82bedeac-9837-5b62-883a-b5b3b7c811c5"

[targets]
test = ["Jute", "BenchmarkTools"]
